# -*- coding: utf-8 -*-
"""Entidad_Parametro_ProyectoUnidad1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Q7v_JoVmUs8znLxmGpM31fRHAuQA7vGV
"""

!pip install Faker
import pandas as pd
import uuid
import random
from faker import Faker
import datetime

num_usuarios = 5000

# A list of 10 features
features = [
    "id_Parametro",
    "Nombre_Parametro",
    "Descripcion_Parametro",
    "Base_Legal_Parametro" ,
    "Fecha_Declaracion_Parametro",
   "Fecha_Derrogacion_Parametro"

]# Creating a DF for these features
df = pd.DataFrame(columns=features)

df['id_Parametro'] = [uuid.uuid4().hex for i in range(num_usuarios)]

print(df['id_Parametro'].nunique()==num_usuarios)

parametros = ["Credito de desarrollo humano ","Bono de desarrollo humano",]

df['Nombre_Parametro'] = random.choices(parametros, weights=(3000,2000), k=num_usuarios)

faker = Faker()
df['Descripcion_Parametro']=[faker.sentence() for i in range(num_usuarios)]

Base = ["MIES","Programa toda una vida"]

df['Base_Legal_Parametro'] = random.choices( Base,  weights=(3500, 1500), k=num_usuarios)

def declaracion(start, end, n):
    """
    Generating a list of a set number of timestamps
    """
    
    # The timestamp format
    frmt = "%Y-%m-%d"
    
    # Formatting the two time periods
    stime = datetime.datetime.strptime(start, frmt)
    etime = datetime.datetime.strptime(end, frmt)
    
    # Creating the pool for random times
    td = etime - stime
    
    # Generating a list with the random times
    times = [(random.random() * td + stime).strftime(frmt) for _ in range(n)]
    
    return times

df['Fecha_Declaracion_Parametro'] = declaracion("2001-01-01", "2013-01-01", num_usuarios)

def Derrogacion(start, end, n):
    """
    Generating a list of a set number of timestamps
    """
    
    # The timestamp format
    frmt = "%Y-%m-%d"
    
    # Formatting the two time periods
    stime = datetime.datetime.strptime(start, frmt)
    etime = datetime.datetime.strptime(end, frmt)
    
    # Creating the pool for random times
    td = etime - stime
    
    # Generating a list with the random times
    times = [(random.random() * td + stime).strftime(frmt) for _ in range(n)]
    
    return times

df['Fecha_Derrogacion_Parametro'] = Derrogacion("2013-01-01", "2022-01-01", num_usuarios)

df.to_csv('Parametros.csv')