# -*- coding: utf-8 -*-
"""Entidad_Proyecto_ProyectoUnidad1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1DtGBHSwCFmxQ0GrooUrOJ9jCUxFzvWwW
"""

!pip install Faker
import pandas as pd
import uuid
import random
from faker import Faker
import datetime

num_usuarios = 5000

# A list of 10 features
features = [
    "id_Proyecto",
    "Nombre_Proyecto",
    "Tipo_Proyecto",
    "Status_Proyecto" 

]# Creating a DF for these features
df = pd.DataFrame(columns=features)

df['id_Proyecto'] = [uuid.uuid4().int for i in range(num_usuarios)]

print(df['id_Proyecto'].nunique()==num_usuarios)

faker = Faker( )
df['Nombre_Proyecto']=[faker.job() for i in range(num_usuarios)]

proyectos = ["Emprendimiento", "Economico","Social", "Politico"]

df['Tipo_Proyecto'] = random.choices(
    proyectos, 
    weights=(2000,500, 1000, 1500), 
    k=num_usuarios
)

status = ["Aceptado", "Rechazado","Pendiente"]

df['Status_Proyecto'] = random.choices(
    status, 
    weights=(2000,1500, 1500), 
    k=num_usuarios
)

df.to_csv('Proyectos.csv')