# -*- coding: utf-8 -*-
"""Entidad_Servicio_ProyectoUnidad1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1TeLXPimyN8WkcWqfRslwsWX8DiSpaDZK
"""

!pip install Faker
import pandas as pd
import uuid
import random
from faker import Faker
import datetime

num_usuarios = 5000

# A list of 10 features
features = [
    "id_Servicio",
    "Nombre_Servicio",
    "Descripcion_Servicio",
    "Status_Servicio",
    "Tipo_Servicio",
    "Monto_Servicio",
    "Fecha_Servicio" 

]# Creating a DF for these features
df = pd.DataFrame(columns=features)

df['id_Servicio'] = [uuid.uuid4().int for i in range(num_usuarios)]

print(df['id_Servicio'].nunique()==num_usuarios)

#Al ser un proyecto basado en el estado unicamente receptaremos datos de genero binario
servicios = ["Atencion al socio", " Credito de desarrollo humano", "Transacciones"]

df['Nombre_Servicio'] = random.choices(
    servicios, 
    weights=(500,2500 ,2000), 
    k=num_usuarios
)

faker = Faker()
df['Descripcion_Servicio']=[faker.sentence() for i in range(num_usuarios)]

status = ["Realizado", "Rechazado", "En espera.."]

df['Status_Servicio'] = random.choices(
    status, 
    weights=(2500,500, 1500), 
    k=num_usuarios
)

tipo = ["Debito", "Credito", "Consulta","Aporte"]

df['Tipo_Servicio'] = random.choices(
    tipo, 
    weights=(2500,1000, 1000,500), 
    k=num_usuarios
)

Monto = ["$2000", "$1200", "$600"]

df['Monto_Servicio'] = random.choices(
    Monto, 
    weights=(2500,500, 2000), 
    k=num_usuarios
)

def random_dob(start, end, n):
    """
    Generating a list of a set number of timestamps
    """
    
    # The timestamp format
    frmt = "%Y-%m-%d"
    
    # Formatting the two time periods
    stime = datetime.datetime.strptime(start, frmt)
    etime = datetime.datetime.strptime(end, frmt)
    
    # Creating the pool for random times
    td = etime - stime
    
    # Generating a list with the random times
    times = [(random.random() * td + stime).strftime(frmt) for _ in range(n)]
    
    return times

df['Fecha_Servicio'] = random_dob("2000-01-01", "2022-01-01", num_usuarios)

df.to_csv('Servicios.csv')