# -*- coding: utf-8 -*-
"""Entidad_Proyecto_ProyectoUnidad1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1DtGBHSwCFmxQ0GrooUrOJ9jCUxFzvWwW
"""
#Importamos e instalamos las librerias necesarias 
!pip install Faker
#Nos ayuda a crear datframe
import pandas as pd
#Genera una cadena de caracteres
import uuid
#Crea datos random
import random
#Describe datos falsos
from faker import Faker
#Nos ayuda a trabajar con la fecha y hora 
import datetime

#Se declara y se define la cantidad de datos que deseamos visualizar
num_usuarios = 5000

#Creamos una lista con los atributos de nuestra entidad
features = [
    "id_Proyecto",
    "Nombre_Proyecto",
    "Tipo_Proyecto",
    "Status_Proyecto" 

]# Creamos nuestra tabla con los atributos previmente definidos
df = pd.DataFrame(columns=features)

df['id_Proyecto'] = [uuid.uuid4().int for i in range(num_usuarios)]
#Comprobamos que los datos generados sean unicos 
print(df['id_Proyecto'].nunique()==num_usuarios)

#Inicalizamos la función faker
faker = Faker( )
#El faker.job nos ayuda a crear trabajos falsos como datos 
df['Nombre_Proyecto']=[faker.job() for i in range(num_usuarios)]

#Definimos los tipos de proyectos que se pueden presentar 
proyectos = ["Emprendimiento", "Economico","Social", "Politico"]

df['Tipo_Proyecto'] = random.choices(
    proyectos, 
    weights=(2000,500, 1000, 1500), 
    k=num_usuarios
)


#Definimos los estados en los que puede estar un proyecto 
status = ["Aceptado", "Rechazado","Pendiente"]

df['Status_Proyecto'] = random.choices(
    status, 
    weights=(2000,1500, 1500), 
    k=num_usuarios
)

#Describimos el tipo de documento donde vamosa almacenar nuestros datos 
df.to_csv('Proyectos.csv')
