# -*- coding: utf-8 -*-
"""Entidad_Amortizacion_ProyectoUnidad1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1DUnmp5_2uABtRLc74LcEJZm_PHJJB-IK
"""

!pip install Faker
import pandas as pd
import uuid
import random
from faker import Faker
import datetime

num_usuarios = 5000

# A list of 10 features
features = [
    "N°_Operacion",
    "Fecha_Pago",
    "Monto_Capital",
    "Interes", 
    "Cuota_Mensual",
    "Estado",

]# Creating a DF for these features
df = pd.DataFrame(columns=features)

df['N°_Operacion'] = [uuid.uuid4().hex for i in range(num_usuarios)]

print(df['N°_Operacion'].nunique()==num_usuarios)

def random_dob(start, end, n):
    """
    Generating a list of a set number of timestamps
    """
    
    # The timestamp format
    frmt = "%Y-%m-%d"
    
    # Formatting the two time periods
    stime = datetime.datetime.strptime(start, frmt)
    etime = datetime.datetime.strptime(end, frmt)
    
    # Creating the pool for random times
    td = etime - stime
    
    # Generating a list with the random times
    times = [(random.random() * td + stime).strftime(frmt) for _ in range(n)]
    
    return times

df['Fecha_Pago'] = random_dob("2000-01-01", "2022-01-01", num_usuarios)

Monto = ["$1200", "$2000","$600"]

df['Monto_Capital'] = random.choices(
    Monto, 
    weights=(2500,2000,500), 
    k=num_usuarios
)

interes = ["%8", "%10", "%12"]

df['Interes'] = random.choices(
    interes, 
    weights=(2500,1500,1000), 
    k=num_usuarios
)

cuota= ["$100", "$110", "$150"]

df['Cuota_Mensual'] = random.choices(
    cuota, 
    weights=(2500,1000, 1500), 
    k=num_usuarios
)

Estado = ["Vigente", "No Vigente"]

df['Estado'] = random.choices(
    Estado, 
    weights=(2500,2500), 
    k=num_usuarios
)

df.to_csv('TabladeArmortizacion.csv')